version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15
    container_name: loan_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - loan_network

  # Next.js 应用
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loan_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/loan_db
      - NODE_ENV=production
    depends_on:
      - postgres
    networks:
      - loan_network

volumes:
  postgres_data:

networks:
  loan_network:
    driver: bridge